# -----------------------------------------------------------------------------
# Project : Origin Observer
# File    : crates/oo-rpc/Cargo.toml
# Purpose : Define the oo-rpc crate and its dependencies.
# Author  : İrfan Gedik
# Year    : 2026
# -----------------------------------------------------------------------------

[package]
name = "oo-rpc"
description = "Perform deterministic and attributable JSON-RPC communication."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
oo-core = { path = "../oo-core" }
oo-model = { path = "../oo-model" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

[lints]
workspace = true
